- name: Install chrony package
  package:
          name: "chrony"
          state: present
- name: Implant chrony configuration file
  template:
    src: chronyalpine.conf.j2
    dest: /etc/chrony/chrony.conf
- name: Enable chrony service
  service:
    name: chronyd
    state: started
    enabled: true
